-- Self-study: exam / deadline tracker with AI-generated study plans.
-- Run this in the Supabase SQL Editor.

create table public.study_exams (
  id            uuid primary key default gen_random_uuid(),
  created_at    timestamptz default now(),
  title         text not null,
  exam_date     date,
  hours_per_day numeric,
  topics        text,
  plan          jsonb,          -- generated by the study-plan edge function
  added_via     text default 'web'
);

alter table public.study_exams enable row level security;

create policy "authenticated full access"
on public.study_exams
for all
to authenticated
using (true)
with check (true);
